name: deploy
on:
  push:
    branches:
      - master
jobs:
  npm-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: npm install
      - run: npm run lib
      - run: npm publish --access public
        env:
            NODE_AUTH_TOKEN: ${{secrets.NPM20200828}}

  github-pages-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: buildAndDeploy
        uses: JamesIves/github-pages-deploy-action@master
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: doc
          BUILD_SCRIPT: npm install && npm run styleguide:build
